"""
Code Reviewer Agent (AI-Powered)

Uses Claude API to perform intelligent code review on PR diffs.
Posts review comments as advisory suggestions — does not block merge.
"""
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from shared.github_client import GitHubClient
from shared.stack_detector import detect_stacks

import anthropic


ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
PROMPTS_DIR = Path(__file__).parent / "prompts"


def load_prompt(name: str) -> str:
    """Load a prompt file from the prompts/ directory."""
    path = PROMPTS_DIR / name
    if path.exists():
        return path.read_text()
    return ""


def build_review_prompt(diff: str, stacks: set[str], files: list[dict]) -> str:
    """Build the full prompt for Claude including stack-specific guidelines."""
    system = load_prompt("system.md")

    # Add stack-specific guidelines
    stack_guidelines = []
    for stack in stacks:
        guide = load_prompt(f"{stack}.md")
        if guide:
            stack_guidelines.append(guide)

    # Build file context
    file_summary = "\n".join(
        f"- `{f['filename']}` ({f.get('status', 'modified')}, +{f.get('additions', 0)}/-{f.get('deletions', 0)})"
        for f in files
    )

    user_prompt = f"""Review the following pull request diff.

## Changed Files
{file_summary}

## Stack-Specific Guidelines
{chr(10).join(stack_guidelines) if stack_guidelines else "No stack-specific guidelines loaded."}

## Diff
```diff
{diff}
```

Provide your review as structured JSON with this format:
{{
  "summary": "One paragraph overall assessment",
  "comments": [
    {{
      "path": "path/to/file.py",
      "line": 42,
      "severity": "suggestion|warning|issue",
      "message": "Your comment here with code suggestion if applicable"
    }}
  ],
  "approval": "approve|request_changes|comment"
}}
"""
    return system, user_prompt


def run_code_review(
    repo: str,
    pr_number: int,
    head_sha: str,
    changed_files: list[str],
    stacks: set[str],
) -> dict:
    """
    Run AI-powered code review on a PR.
    Posts review comments on the PR (advisory, non-blocking).
    """
    gh = GitHubClient(repo)

    # Get the diff and file details
    diff = gh.get_pr_diff(pr_number)
    files = gh.get_pr_files(pr_number)

    # Truncate diff if too large (Claude context window)
    MAX_DIFF_CHARS = 80_000
    if len(diff) > MAX_DIFF_CHARS:
        diff = diff[:MAX_DIFF_CHARS] + "\n\n... [diff truncated — too large for review]"

    # Build prompt
    system_prompt, user_prompt = build_review_prompt(diff, stacks, files)

    # Call Claude API
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=4096,
        system=system_prompt,
        messages=[{"role": "user", "content": user_prompt}],
    )

    review_text = response.content[0].text

    # Try to parse structured response
    import json
    try:
        # Extract JSON from response (it might be wrapped in markdown)
        json_match = review_text
        if "```json" in review_text:
            json_match = review_text.split("```json")[1].split("```")[0]
        elif "```" in review_text:
            json_match = review_text.split("```")[1].split("```")[0]

        review = json.loads(json_match)

        # Post inline comments
        for comment in review.get("comments", []):
            try:
                severity_emoji = {
                    "suggestion": "💡",
                    "warning": "⚠️",
                    "issue": "🔴"
                }.get(comment.get("severity", ""), "💬")

                gh.post_review_comment(
                    pr_number=pr_number,
                    body=f"{severity_emoji} **{comment.get('severity', 'comment').title()}**: {comment['message']}",
                    commit_sha=head_sha,
                    path=comment["path"],
                    line=comment["line"],
                )
            except Exception:
                # If inline comment fails (line might not be in diff), post as general comment
                pass

        # Post summary comment
        marker = "<!-- agent:code-reviewer -->"
        summary_body = f"""{marker}
## 🤖 AI Code Review

{review.get('summary', 'No summary available.')}

**Recommendation:** {review.get('approval', 'comment')}

---
<sub>This review was generated by the NetZero Code Reviewer agent. It is advisory — human reviewers make the final decision.</sub>
"""
        gh.update_or_create_comment(pr_number, summary_body, marker)

        return {"status": "success", "comments": len(review.get("comments", []))}

    except (json.JSONDecodeError, IndexError, KeyError):
        # If JSON parsing fails, post the raw review as a comment
        marker = "<!-- agent:code-reviewer -->"
        body = f"""{marker}
## 🤖 AI Code Review

{review_text}

---
<sub>This review was generated by the NetZero Code Reviewer agent.</sub>
"""
        gh.update_or_create_comment(pr_number, body, marker)
        return {"status": "success", "comments": 0, "format": "raw"}
