"""
PR Summarizer Agent (AI-Powered)

Automatically generates a human-readable summary of what a PR does.
Posts a comment with summary, risk assessment, and suggested reviewers.
"""
import os
import sys
import json
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from shared.github_client import GitHubClient
from shared.stack_detector import detect_stacks

import anthropic

ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")


SYSTEM_PROMPT = """You are a technical writer at NetZero. Your job is to summarize pull requests
so that reviewers can quickly understand what changed and why.

Generate a summary with:
1. A one-paragraph description of the change (what and why)
2. A list of changed files with a brief description of each change
3. A risk assessment: LOW (cosmetic/docs), MEDIUM (new feature, well-tested), HIGH (core logic, security, data)
4. Which layers are touched (Presentation, Application, Domain, Infrastructure)

Format as JSON:
{
  "summary": "paragraph",
  "file_changes": [{"file": "path", "description": "what changed"}],
  "risk": "LOW|MEDIUM|HIGH",
  "risk_reason": "why",
  "layers_touched": ["Presentation", "Application"],
  "stacks": ["python", "javascript"]
}
"""


def run_pr_summary(
    repo: str,
    pr_number: int,
    head_sha: str,
    changed_files: list[str],
    stacks: set[str],
) -> dict:
    """Generate and post a PR summary."""
    gh = GitHubClient(repo)

    diff = gh.get_pr_diff(pr_number)
    files = gh.get_pr_files(pr_number)

    # Truncate if needed
    MAX_CHARS = 60_000
    if len(diff) > MAX_CHARS:
        diff = diff[:MAX_CHARS] + "\n... [truncated]"

    file_list = "\n".join(
        f"- `{f['filename']}` ({f.get('status', 'modified')}, +{f.get('additions', 0)}/-{f.get('deletions', 0)})"
        for f in files
    )

    user_prompt = f"""Summarize this pull request.

## Changed Files
{file_list}

## Stacks Detected
{', '.join(stacks)}

## Diff
```diff
{diff}
```
"""

    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=2048,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": user_prompt}],
    )

    result_text = response.content[0].text

    # Parse JSON
    try:
        if "```json" in result_text:
            result_text = result_text.split("```json")[1].split("```")[0]
        elif "```" in result_text:
            result_text = result_text.split("```")[1].split("```")[0]
        data = json.loads(result_text)
    except (json.JSONDecodeError, IndexError):
        data = {"summary": result_text, "risk": "UNKNOWN", "file_changes": []}

    # Build comment
    risk_emoji = {"LOW": "🟢", "MEDIUM": "🟡", "HIGH": "🔴"}.get(data.get("risk", ""), "⚪")

    file_changes = "\n".join(
        f"| `{fc.get('file', '')}` | {fc.get('description', '')} |"
        for fc in data.get("file_changes", [])
    )

    layers = ", ".join(data.get("layers_touched", []))
    stacks_str = ", ".join(data.get("stacks", list(stacks)))

    marker = "<!-- agent:pr-summarizer -->"
    body = f"""{marker}
## 📋 PR Summary

{data.get('summary', 'No summary available.')}

### Risk Assessment
{risk_emoji} **{data.get('risk', 'UNKNOWN')}** — {data.get('risk_reason', '')}

### Details
| File | Change |
|------|--------|
{file_changes}

**Layers touched:** {layers or 'N/A'}
**Stacks:** {stacks_str}

---
<sub>Generated by the NetZero PR Summarizer agent.</sub>
"""

    gh.update_or_create_comment(pr_number, body, marker)
    return {"status": "success", "risk": data.get("risk", "UNKNOWN")}
